apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-model-cache
  namespace: gemma-system
  labels:
    app: gemma-server
    demo: argo-rollouts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo
