apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-1b-model-cache
  namespace: gemma-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-9b-model-cache
  namespace: gemma-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 60Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-27b-model-cache
  namespace: gemma-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 150Gi
